p2p_no_group_iface=1
p2p_disabled=1
update_config=1
pmf=1
driver_param=p2p_no_group_iface=1
ctrl_interface=wlan0
p2p_listen_reg_class=81
p2p_listen_channel=1
p2p_oper_reg_class=124
p2p_oper_channel=149
bss_no_flush_when_down=1
p2p_add_cli_chan=1
